/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aiyou_ptt_AudioOpusJni */

#ifndef _Included_com_aiyou_ptt_AudioOpusJni
#define _Included_com_aiyou_ptt_AudioOpusJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    audioModuleInit
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_audioModuleInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    pttLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIZLjava/lang/String;ZLjava/lang/String;Ljava/lang/String;DD)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_pttLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jint, jint, jboolean, jstring, jboolean, jstring, jstring, jdouble, jdouble);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    pttLogout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_pttLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    setVolumeEnable
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_setVolumeEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    startSendAudio
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_startSendAudio
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    stopSendAudio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_stopSendAudio
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    startRecvAudio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_startRecvAudio
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    stopRecvAudio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_stopRecvAudio
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    pttGetUpUserList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_aiyou_ptt_AudioOpusJni_pttGetUpUserList
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    talkCallout
 * Signature: (ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_talkCallout
  (JNIEnv *, jobject, jboolean, jstring, jobject, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    talkAccept
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_talkAccept
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    talkCancel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_talkCancel
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    talkRefuse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_talkRefuse
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    talkHangup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_talkHangup
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIZZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jint, jint, jboolean, jboolean, jstring);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicLogout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicOpenRemoteVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicOpenRemoteVideo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicResetRemoteVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicResetRemoteVideo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicCloseRemoteVideo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicCloseRemoteVideo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicOpenLocalVideo
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicOpenLocalVideo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    LinkMicCloseLocalVideo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_LinkMicCloseLocalVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;DD)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint, jint, jint, jboolean, jstring, jstring, jstring, jdouble, jdouble);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLogout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfCreate
 * Signature: (Ljava/lang/String;ZI)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfCreate
  (JNIEnv *, jobject, jstring, jboolean, jint);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfJoin
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfJoin
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfExit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfExit
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfInviteMember
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfInviteMember
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfKickMember
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfKickMember
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLocalVideoSetParam
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLocalVideoSetParam
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLocalVideoOpen
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLocalVideoOpen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLocalVideoClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLocalVideoClose
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfPeerVideoOpen
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfPeerVideoOpen
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfPeerVideoClose
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfPeerVideoClose
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLocalMicMute
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLocalMicMute
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfPeerMicMute
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfPeerMicMute
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLocalVideoSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLocalVideoSwitch
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfLocalNetworkChanged
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfLocalNetworkChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_aiyou_ptt_AudioOpusJni
 * Method:    ConfGetUpUserList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_aiyou_ptt_AudioOpusJni_ConfGetUpUserList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
